insert into sistemas (url,nombre,estado)values('http://intranet.smr.edu.pe/','Colegio Santa María Reyna',1);
insert into sistemas (url,nombre,estado)values('http://andresbelloarequipa.apae.com.pe/','AB Arequipa',1);
insert into sistemas (url,nombre,estado)values('http://andresbellochimbote.apae.com.pe/','AB Chimbote',1);
insert into sistemas (url,nombre,estado)values('http://andresbelloica.apae.com.pe/','AB Ica',1);
insert into sistemas (url,nombre,estado)values('http://andresbellolima.apae.com.pe','AB Lima',1);
insert into sistemas (url,nombre,estado)values('http://andresbellopiura.apae.com.pe/','AB Piura',1);
insert into sistemas (url,nombre,estado)values('http://andresbellotacna.apae.com.pe/','AB Tacna',1);
insert into sistemas (url,nombre,estado)values('http://andresbellotrujillo.apae.com.pe/','AB Trujillo',1);
insert into sistemas (url,nombre,estado)values('http://silchiclayo.apae.com.pe/','SIL Chiclayo',1);
insert into sistemas (url,nombre,estado)values('http://silchorrillos.apae.com.pe/','SIL Chorrillos',1);
insert into sistemas (url,nombre,estado)values('http://siltrujillo.apae.com.pe/','SIL Trujillo',1);
insert into sistemas (url,nombre,estado)values('http://silmiraflores.apae.com.pe/','SIL  Miraflores',1);
insert into sistemas (url,nombre,estado)values('http://sanignaciodejesus.apae.com.pe/','SIJ Arequipa',1);
insert into sistemas (url,nombre,estado)values('http://sanignaciodejesuslima.apae.com.pe/','SIJ Lima',1);
insert into sistemas (url,nombre,estado)values('http://sanjuanbosco.mastabeats.com/','SJB',1);
insert into sistemas (url,nombre,estado)values('http://mariadelsocorro.apae.com.pe/','Maria del Socorro',1);
insert into sistemas (url,nombre,estado)values('http://cebasanignaciodejesus.apae.com.pe/','CEBA SIJ',1);
insert into sistemas (url,nombre,estado)values('http://cebasilmiraflores.apae.com.pe/','CEBA SIL Miraflores',1);
insert into sistemas (url,nombre,estado)values('http://liceofemenimoandresbello.apae.com.pe/','Liceo',1);
insert into sistemas (url,nombre,estado)values('http://peadandresbello.apae.com.pe/','PEAD AB',1);
insert into sistemas (url,nombre,estado)values('http://colegiociencias.apae.com.pe/','Colegio Ciencias',1);
insert into sistemas (url,nombre,estado)values('http://cetprotacna.mastabeats.com/','Hispano Americano',1);
insert into sistemas (url,nombre,estado)values('http://imprenta.apae.com.pe/','Imprenta',1);